#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app:
  path: /
  controller: App\Controller\AppController::home
app_contact:
  path: /contact
  controller: App\Controller\AppController::contact